tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/services"
brew "bat"
brew "exa"
brew "git"
brew "httpie"
brew "mas"
brew "eth-p/software/bat-extras"
cask "alt-tab"
cask "dbngin"
cask "discord"
cask "docker"
cask "firefox"
cask "fliqlo"
cask "folx"
cask "gitkraken"
cask "google-chrome"
cask "hiddenbar"
cask "optimus-player"
cask "postman"
cask "raycast"
cask "rectangle"
cask "signal"
cask "tableplus"
cask "tg-pro"
cask "visual-studio-code"
cask "warp"
mas "ClearVPN", id: 1531601984
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
vscode "entuent.fira-code-nerd-font"
vscode "file-icons.file-icons"
vscode "idbartosz.darkpp-italic"
