#Change ZSH Options
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
export PATH=$ANDROID_HOME/emulator:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH
#Create Aliases
alias lls='eza -lahg --git --icons'
alias bbd='brew bundle dump -f --describe'
alias lzd=lazydocker
alias trail='<<<${(F)path}'
alias lzg=lazygit
alias rm=trash
#Add location to the path array variables
typeset -U path
path=(
  "$N_PREFIX/bin"
  $path
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
)
#use ZSH plugins
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
eval "$(starship init zsh)"

